ALTER TABLE car ADD COLUMN release INT;
ALTER TABLE car ADD COLUMN shape VARCHAR;
ALTER TABLE car ADD COLUMN drive VARCHAR;
ALTER TABLE car ADD COLUMN gsb VARCHAR;
ALTER TABLE car ADD COLUMN color VARCHAR;
ALTER TABLE car ADD COLUMN mileage INT;


